#!/usr/bin/python
import socket
import threading


def forward(uploader, downloader):
    while 1:
        data = uploader.recv(1024)

        if len(data) == 0:
            break
        else:
            downloader.send(data)

    uploader.close()
    downloader.close()


def server_run():
    download_list = []
    connect_list =[]
    thread_list = []
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("",0))

    port_number = sock.getsockname()[1]

    f = open("port", "w")
    f.write(str(port_number))

    f.close()
    print("OS-Assigned port: " + str(port_number) + "\n")

    while 1:
        sock.listen(1)
        conn, connect_address = sock.accept()

        source = conn.recv(9)
        key = source[1:]

        if source[0] == 'F':
            print("server termination starts\n")
            while len(connect_list) != 0:
                connect_list[0].close()
                del download_list[0]
                del connect_list[0]

            for x in range(0,len(thread_list)):
                thread_list[x].join()

            print("server termination ended\n")
            break
        elif source[0] == 'P':
            if key in download_list:
                key_index = download_list.index(key)
                target = connect_list[key_index]

                t = threading.Thread(None,forward,None,(conn,target))
                t.start()
                thread_list.append(t)

                del download_list[key_index]
                del connect_list[key_index]
        elif source[0] == 'G':
            download_list.append(key)
            connect_list.append(conn)

    sock.close()


server_run()